### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by hoZla2222** [Xeift/Metamask-Mnemonic-Brute-Force#2]
**he show me this when i run it bdw i run it with replit** 

Hint: hit control+c anytime to enter REPL.
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/runner/YawningProfitableInformation/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange (/home/runner/YawningProfitableInformation/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/runner/YawningProfitableInformation/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/runner/YawningProfitableInformation/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/home/runner/YawningProfitableInformation/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/home/runner/YawningProfitableInformation/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
repl process died unexpectedly: exit status 1


**Comment by Xeift** [comment]
can you screenshot or paste your code?

**Comment by Xeift** [comment]
try uninstall nodejs and install 16.14.2 LTS
![image](https://user-images.githubusercontent.com/80938768/164694963-32d643d7-b0c5-4014-9a24-f1fa3cadd903.png)

**Comment by sananepilader** [comment]
ok I try
Thank You

**Comment by sananepilader** [comment]
same problem bro
look pleas
![Screenshot_1 (2)](https://user-images.githubusercontent.com/102332927/164703776-3bbb7733-5d3f-4766-b2f2-df8f45751cbc.png)
e

**Comment by Xeift** [comment]
hmmm
use alchemy if infura not work
