### ISSUE TITLE
cannot run it

### ISSUE THREAD

**Issue by PICwarior381-Coder** [Xeift/Metamask-Mnemonic-Brute-Force#3]
I'am unable to run the program
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (C:\Users\user\node_modules\web3-core-helpers\lib\errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange (C:\Users\user\node_modules\web3-providers-http\lib\index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\user\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (C:\Users\user\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (C:\Users\user\node_modules\xhr2-cookies\dist\xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (C:\Users\user\node_modules\xhr2-cookies\dist\xml-http-request.js:252:61)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

This is my code
![image](https://user-images.githubusercontent.com/13154159/167271051-5ff11705-2ded-4698-aeaf-ae53730fcdf7.png)
I also tried with Alchemy but doesn't work, I tried on repl.it same thing

**Comment by Xeift** [comment]
https://github.com/Xeift/Metamask-Mnemonic-Brute-Force/issues/1

**Comment by PICwarior381-Coder** [comment]
Well I did that, but it doesn't work am'I missing something here?
